create database opencart;

GRANT ALL PRIVILEGES ON opencart.* TO 'opencart_ower'@'%' IDENTIFIED BY '$eattle2006$$' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON greeting_card.* TO 'greetingcard_owner'@'%' IDENTIFIED BY '$eattle2006$$' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON opencart2.* TO 'greetingcard_owner'@'%' IDENTIFIED BY '$eattle2006$$' WITH GRANT OPTION;

truncate table oc_category;
truncate table oc_category_description;
truncate table oc_category_path;
truncate table oc_category_to_store;

truncate table oc_product;
truncate table oc_product_description;
truncate table oc_product_to_store;
truncate table oc_product_image;
truncate table oc_product_special;
truncate table oc_product_to_category;
commit;



truncate table oc_banner;
INSERT INTO `oc_banner` (banner_id,name,status) VALUES (6,'SubBanner',1);
INSERT INTO `oc_banner` (banner_id,name,status) VALUES (7,'Home Page Slideshow',1);
INSERT INTO `oc_banner` (banner_id,name,status) VALUES (8,'Manufacturers',1);
INSERT INTO `oc_banner` (banner_id,name,status) VALUES (9,'Left Banner',1);
INSERT INTO `oc_banner` (banner_id,name,status) VALUES (10,'Rightbanner1',1);
INSERT INTO `oc_banner` (banner_id,name,status) VALUES (11,'Rightbanner2',1);
commit;


truncate table oc_banner_image;
INSERT INTO `oc_banner_image` (banner_image_id,banner_id,language_id,title,link,image,sort_order) VALUES (101,9,1,'test','','',0);
INSERT INTO `oc_banner_image` (banner_image_id,banner_id,language_id,title,link,image,sort_order) VALUES (114,10,1,'Rightbanner1','','catalog/right_banner.jpg',0);
INSERT INTO `oc_banner_image` (banner_image_id,banner_id,language_id,title,link,image,sort_order) VALUES (115,11,1,'Rightbanner2','','catalog/right_banner2.jpg',0);
INSERT INTO `oc_banner_image` (banner_image_id,banner_id,language_id,title,link,image,sort_order) VALUES (121,6,1,'SubBanner','index.php?route=product/manufacturer/info&amp;manufacturer_id=7','catalog/small_banner.jpg',0);
INSERT INTO `oc_banner_image` (banner_image_id,banner_id,language_id,title,link,image,sort_order) VALUES (122,8,1,'flower','','catalog/images/flower.jpg',0);
INSERT INTO `oc_banner_image` (banner_image_id,banner_id,language_id,title,link,image,sort_order) VALUES (123,8,1,'christmas','','catalog/images/christmas.jpg',0);
INSERT INTO `oc_banner_image` (banner_image_id,banner_id,language_id,title,link,image,sort_order) VALUES (124,8,1,'birthday','','catalog/images/birthday21.jpg',0);
INSERT INTO `oc_banner_image` (banner_image_id,banner_id,language_id,title,link,image,sort_order) VALUES (125,8,1,'congratulation','','catalog/images/congratulations.jpg',0);
INSERT INTO `oc_banner_image` (banner_image_id,banner_id,language_id,title,link,image,sort_order) VALUES (129,7,1,'greeting card1','','catalog/mainbanner3.jpg',0);
INSERT INTO `oc_banner_image` (banner_image_id,banner_id,language_id,title,link,image,sort_order) VALUES (130,7,1,'Animal','index.php?route=product/product&amp;path=57&amp;product_id=49','catalog/images/bird.jpg',0);
commit;



truncate table oc_extension;
INSERT INTO `oc_extension` (extension_id,type,code) VALUES (1,'payment','cod');
INSERT INTO `oc_extension` (extension_id,type,code) VALUES (2,'total','shipping');
INSERT INTO `oc_extension` (extension_id,type,code) VALUES (3,'total','sub_total');
INSERT INTO `oc_extension` (extension_id,type,code) VALUES (4,'total','tax');
INSERT INTO `oc_extension` (extension_id,type,code) VALUES (5,'total','total');
INSERT INTO `oc_extension` (extension_id,type,code) VALUES (6,'module','banner');
INSERT INTO `oc_extension` (extension_id,type,code) VALUES (7,'module','carousel');
INSERT INTO `oc_extension` (extension_id,type,code) VALUES (8,'total','credit');
INSERT INTO `oc_extension` (extension_id,type,code) VALUES (9,'shipping','flat');
INSERT INTO `oc_extension` (extension_id,type,code) VALUES (10,'total','handling');
INSERT INTO `oc_extension` (extension_id,type,code) VALUES (11,'total','low_order_fee');
INSERT INTO `oc_extension` (extension_id,type,code) VALUES (12,'total','coupon');
INSERT INTO `oc_extension` (extension_id,type,code) VALUES (13,'module','category');
INSERT INTO `oc_extension` (extension_id,type,code) VALUES (14,'module','account');
INSERT INTO `oc_extension` (extension_id,type,code) VALUES (15,'total','reward');
INSERT INTO `oc_extension` (extension_id,type,code) VALUES (16,'total','voucher');
INSERT INTO `oc_extension` (extension_id,type,code) VALUES (17,'payment','free_checkout');
INSERT INTO `oc_extension` (extension_id,type,code) VALUES (18,'module','featured');
INSERT INTO `oc_extension` (extension_id,type,code) VALUES (19,'module','slideshow');
INSERT INTO `oc_extension` (extension_id,type,code) VALUES (20,'theme','theme_default');
INSERT INTO `oc_extension` (extension_id,type,code) VALUES (21,'dashboard','activity');
INSERT INTO `oc_extension` (extension_id,type,code) VALUES (22,'dashboard','sale');
INSERT INTO `oc_extension` (extension_id,type,code) VALUES (23,'dashboard','recent');
INSERT INTO `oc_extension` (extension_id,type,code) VALUES (24,'dashboard','order');
INSERT INTO `oc_extension` (extension_id,type,code) VALUES (25,'dashboard','online');
INSERT INTO `oc_extension` (extension_id,type,code) VALUES (26,'dashboard','map');
INSERT INTO `oc_extension` (extension_id,type,code) VALUES (27,'dashboard','customer');
INSERT INTO `oc_extension` (extension_id,type,code) VALUES (28,'dashboard','chart');
INSERT INTO `oc_extension` (extension_id,type,code) VALUES (29,'module','html');
INSERT INTO `oc_extension` (extension_id,type,code) VALUES (30,'module','information');
INSERT INTO `oc_extension` (extension_id,type,code) VALUES (31,'module','newsletters');
INSERT INTO `oc_extension` (extension_id,type,code) VALUES (32,'module','latest');
INSERT INTO `oc_extension` (extension_id,type,code) VALUES (33,'module','special');
INSERT INTO `oc_extension` (extension_id,type,code) VALUES (34,'module','category_tab');
INSERT INTO `oc_extension` (extension_id,type,code) VALUES (35,'module','megnortabs');
INSERT INTO `oc_extension` (extension_id,type,code) VALUES (36,'module','search_suggestion');
INSERT INTO `oc_extension` (extension_id,type,code) VALUES (38,'module','megnorcategory');
INSERT INTO `oc_extension` (extension_id,type,code) VALUES (39,'module','blogger');
INSERT INTO `oc_extension` (extension_id,type,code) VALUES (40,'module','bestseller');
INSERT INTO `oc_extension` (extension_id,type,code) VALUES (41,'module','filter');

truncate table oc_module;
INSERT INTO `oc_module` (module_id,name,code,setting) VALUES (27,'Home Page','slideshow','{"name":"Home Page","banner_id":"7","width":"1140","height":"380","status":"1"}');
INSERT INTO `oc_module` (module_id,name,code,setting) VALUES (28,'Home Page','featured','{"name":"Home Page","product_name":"","product":["43","40","42","30","41","47"],"limit":"7","width":"218","height":"286","status":"1"}');
INSERT INTO `oc_module` (module_id,name,code,setting) VALUES (31,'SubBanner','banner','{"name":"SubBanner","banner_id":"6","width":"914","height":"60","status":"1"}');
INSERT INTO `oc_module` (module_id,name,code,setting) VALUES (32,'HeaderTop-Offer-CMS','html','{"name":"HeaderTop-Offer-CMS","module_description":{"1":{"title":"","description":"&lt;p&gt;&lt;br&gt;&lt;\/p&gt;"}},"status":"1"}');
INSERT INTO `oc_module` (module_id,name,code,setting) VALUES (33,'HomePage-Subbanner2-CMS','html','{"name":"HomePage-Subbanner2-CMS","module_description":{"1":{"title":"","description":"&lt;p&gt;&lt;br&gt;&lt;\/p&gt;"}},"status":"1"}');
INSERT INTO `oc_module` (module_id,name,code,setting) VALUES (34,'HomePage-Subbanner3-CMS ','html','{"name":"HomePage-Subbanner3-CMS ","module_description":{"1":{"title":"","description":"&lt;p&gt;&lt;br&gt;&lt;\/p&gt;"}},"status":"1"}');
INSERT INTO `oc_module` (module_id,name,code,setting) VALUES (35,'HeaderTopLeft-Shipping-CMS ','html','{"name":"HeaderTopLeft-Shipping-CMS ","module_description":{"1":{"title":"","description":"&lt;p&gt;&lt;br&gt;&lt;\/p&gt;"}},"status":"1"}');
INSERT INTO `oc_module` (module_id,name,code,setting) VALUES (36,' HeaderTopRight-Contact-CMS','html','{"name":" HeaderTopRight-Contact-CMS","module_description":{"1":{"title":"","description":"&lt;p&gt;&lt;br&gt;&lt;\/p&gt;"}},"status":"1"}');
INSERT INTO `oc_module` (module_id,name,code,setting) VALUES (37,'HomePage-Category-CMS','html','{"name":"HomePage-Category-CMS","module_description":{"1":{"title":"","description":"&lt;div class=&quot;category-cms&quot;&gt; \r\n&lt;div class=&quot;category-container&quot;&gt; \r\n&lt;div class=&quot;category-row&quot;&gt; \r\n&lt;div class=&quot;categoryblock1 categoryblock&quot;&gt; \r\n&lt;div class=&quot;category&quot;&gt; \r\n&lt;div class=&quot;cat-desc&quot;&gt; \r\n&lt;div class=&quot;cate-heading&quot;&gt;&lt;a href=&quot;#&quot;&gt;mobile&lt;\/a&gt;&lt;\/div&gt;\r\n&lt;ul class=&quot;subcats&quot;&gt;\r\n&lt;li&gt;&lt;a href=&quot;#&quot;&gt;smart&lt;\/a&gt;&lt;\/li&gt;\r\n&lt;li&gt;&lt;a href=&quot;#&quot;&gt;comfortable&lt;\/a&gt;&lt;\/li&gt;\r\n&lt;li&gt;&lt;a href=&quot;#&quot;&gt;stylist&lt;\/a&gt;&lt;\/li&gt;\r\n&lt;li&gt;&lt;a href=&quot;#&quot;&gt;fomforta&lt;\/a&gt;&lt;\/li&gt;\r\n&lt;\/ul&gt;\r\n&lt;\/div&gt;\r\n&lt;div class=&quot;image&quot;&gt;\r\n&lt;a href=&quot;#&quot;&gt;&lt;img src=&quot;image\/catalog\/01.jpg&quot; alt=&quot;&quot; class=&quot;img-responsive&quot;&gt;&lt;\/a&gt;&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;div class=&quot;categoryblock2 categoryblock&quot;&gt; \r\n&lt;div class=&quot;category&quot;&gt; \r\n&lt;div class=&quot;cat-desc&quot;&gt; \r\n&lt;div class=&quot;cate-heading&quot;&gt;&lt;a href=&quot;#&quot;&gt;accessories&lt;\/a&gt;&lt;\/div&gt;\r\n&lt;ul class=&quot;subcats&quot;&gt;\r\n&lt;li&gt;&lt;a href=&quot;#&quot;&gt;chorme&lt;\/a&gt;&lt;\/li&gt;\r\n&lt;li&gt;&lt;a href=&quot;#&quot;&gt;firefox add&lt;\/a&gt;&lt;\/li&gt;\r\n&lt;li&gt;&lt;a href=&quot;#&quot;&gt;nodeJS&lt;\/a&gt;&lt;\/li&gt;\r\n&lt;li&gt;&lt;a href=&quot;#&quot;&gt;tax package&lt;\/a&gt;&lt;\/li&gt;\r\n&lt;\/ul&gt;\r\n&lt;\/div&gt;\r\n&lt;div class=&quot;image&quot;&gt;\r\n&lt;a href=&quot;#&quot;&gt;&lt;img src=&quot;image\/catalog\/02.jpg&quot; alt=&quot;&quot; class=&quot;img-responsive&quot;&gt;&lt;\/a&gt;&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;div class=&quot;categoryblock3 categoryblock&quot;&gt; \r\n&lt;div class=&quot;category&quot;&gt; \r\n&lt;div class=&quot;cat-desc&quot;&gt; \r\n&lt;div class=&quot;cate-heading&quot;&gt;&lt;a href=&quot;#&quot;&gt;furniture&lt;\/a&gt;&lt;\/div&gt;\r\n&lt;ul class=&quot;subcats&quot;&gt;\r\n&lt;li&gt;&lt;a href=&quot;#&quot;&gt;`key`word Prote&lt;\/a&gt;&lt;\/li&gt;\r\n&lt;li&gt;&lt;a href=&quot;#&quot;&gt;laptop bags&lt;\/a&gt;&lt;\/li&gt;\r\n&lt;li&gt;&lt;a href=&quot;#&quot;&gt;latest model&lt;\/a&gt;&lt;\/li&gt;\r\n&lt;li&gt;&lt;a href=&quot;#&quot;&gt;eyword&lt;\/a&gt;&lt;\/li&gt;\r\n&lt;\/ul&gt;\r\n&lt;\/div&gt;\r\n&lt;div class=&quot;image&quot;&gt;\r\n&lt;a href=&quot;#&quot;&gt;&lt;img src=&quot;image\/catalog\/03.jpg&quot; alt=&quot;&quot; class=&quot;img-responsive&quot;&gt;&lt;\/a&gt;&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;div class=&quot;categoryblock4 categoryblock&quot;&gt; \r\n&lt;div class=&quot;category&quot;&gt; \r\n&lt;div class=&quot;cat-desc&quot;&gt; \r\n&lt;div class=&quot;cate-heading&quot;&gt;&lt;a href=&quot;#&quot;&gt;Kitchen&lt;\/a&gt;&lt;\/div&gt;\r\n&lt;ul class=&quot;subcats&quot;&gt;\r\n&lt;li&gt;&lt;a href=&quot;#&quot;&gt;microwave&lt;\/a&gt;&lt;\/li&gt;\r\n&lt;li&gt;&lt;a href=&quot;#&quot;&gt;cooktops&lt;\/a&gt;&lt;\/li&gt;\r\n&lt;li&gt;&lt;a href=&quot;#&quot;&gt;juicer Grinders&lt;\/a&gt;&lt;\/li&gt;\r\n&lt;li&gt;&lt;a href=&quot;#&quot;&gt;Electric cookers&lt;\/a&gt;&lt;\/li&gt;\r\n&lt;\/ul&gt;\r\n&lt;\/div&gt;\r\n&lt;div class=&quot;image&quot;&gt;\r\n&lt;a href=&quot;#&quot;&gt;&lt;img src=&quot;image\/catalog\/04.jpg&quot; alt=&quot;&quot; class=&quot;img-responsive&quot;&gt;&lt;\/a&gt;&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;div class=&quot;categoryblock5 categoryblock&quot;&gt; \r\n&lt;div class=&quot;category&quot;&gt; \r\n&lt;div class=&quot;cat-desc&quot;&gt; \r\n&lt;div class=&quot;cate-heading&quot;&gt;&lt;a href=&quot;#&quot;&gt;computers&lt;\/a&gt;&lt;\/div&gt;\r\n&lt;ul class=&quot;subcats&quot;&gt;\r\n&lt;li&gt;&lt;a href=&quot;#&quot;&gt;laptop&lt;\/a&gt;&lt;\/li&gt;\r\n&lt;li&gt;&lt;a href=&quot;#&quot;&gt;computer&lt;\/a&gt;&lt;\/li&gt;\r\n&lt;li&gt;&lt;a href=&quot;#&quot;&gt;network&lt;\/a&gt;&lt;\/li&gt;\r\n&lt;li&gt;&lt;a href=&quot;#&quot;&gt;computer&lt;\/a&gt;&lt;\/li&gt;\r\n&lt;\/ul&gt;\r\n&lt;\/div&gt;\r\n&lt;div class=&quot;image&quot;&gt;\r\n&lt;a href=&quot;#&quot;&gt;&lt;img src=&quot;image\/catalog\/05.jpg&quot; alt=&quot;&quot; class=&quot;img-responsive&quot;&gt;&lt;\/a&gt;&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;div class=&quot;categoryblock6 categoryblock&quot;&gt; \r\n&lt;div class=&quot;category&quot;&gt; \r\n&lt;div class=&quot;cat-desc&quot;&gt; \r\n&lt;div class=&quot;cate-heading&quot;&gt;&lt;a href=&quot;#&quot;&gt;cosmetics&lt;\/a&gt;&lt;\/div&gt;\r\n&lt;ul class=&quot;subcats&quot;&gt;\r\n&lt;li&gt;&lt;a href=&quot;#&quot;&gt;skin care&lt;\/a&gt;&lt;\/li&gt;\r\n&lt;li&gt;&lt;a href=&quot;#&quot;&gt;beauty products&lt;\/a&gt;&lt;\/li&gt;\r\n&lt;li&gt;&lt;a href=&quot;#&quot;&gt;no side effects&lt;\/a&gt;&lt;\/li&gt;\r\n&lt;li&gt;&lt;a href=&quot;#&quot;&gt;products&lt;\/a&gt;&lt;\/li&gt;\r\n&lt;\/ul&gt;\r\n&lt;\/div&gt;\r\n&lt;div class=&quot;image&quot;&gt;\r\n&lt;a href=&quot;#&quot;&gt;&lt;img src=&quot;image\/catalog\/06.jpg&quot; alt=&quot;&quot; class=&quot;img-responsive&quot;&gt;&lt;\/a&gt;&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;\/div&gt;"}},"status":"1"}');
INSERT INTO `oc_module` (module_id,name,code,setting) VALUES (38,'Footer-Bottom-CMS ','html','{"name":"Footer-Bottom-CMS ","module_description":{"1":{"title":"","description":"&lt;div class=&quot;footerbottom-cms&quot;&gt;\r\n&lt;div class=&quot;social-cms&quot;&gt; \r\n&lt;ul class=&quot;social&quot;&gt;\r\n&lt;li class=&quot;facebook&quot;&gt;&lt;a href=&quot;#&quot;&gt;&lt;\/a&gt;&lt;\/li&gt;\r\n&lt;li class=&quot;twitter&quot;&gt;&lt;a href=&quot;#&quot;&gt;&lt;\/a&gt;&lt;\/li&gt;\r\n&lt;li class=&quot;gplus&quot;&gt;&lt;a href=&quot;#&quot;&gt;&lt;\/a&gt;&lt;\/li&gt;\r\n&lt;li class=&quot;linkedin&quot;&gt;&lt;a href=&quot;#&quot;&gt;&lt;\/a&gt;&lt;\/li&gt;\r\n&lt;\/ul&gt;\r\n&lt;\/div&gt;\r\n&lt;div class=&quot;app-cms&quot;&gt;\r\n&lt;ul class=&quot;app&quot;&gt;\r\n&lt;li class=&quot;playstore&quot;&gt;&lt;a href=&quot;#&quot;&gt;&lt;\/a&gt;&lt;\/li&gt;\r\n&lt;li class=&quot;appstore&quot;&gt;&lt;a href=&quot;#&quot;&gt;&lt;\/a&gt;&lt;\/li&gt;\r\n&lt;li class=&quot;windowsstore&quot;&gt;&lt;a href=&quot;#&quot;&gt;&lt;\/a&gt;&lt;\/li&gt;\r\n&lt;\/ul&gt;\r\n&lt;\/div&gt;\r\n&lt;div class=&quot;payment-cms&quot;&gt; \r\n&lt;ul class=&quot;payment&quot;&gt;\r\n&lt;li class=&quot;visa&quot;&gt;&lt;a href=&quot;#&quot;&gt;&lt;\/a&gt;&lt;\/li&gt;\r\n&lt;li class=&quot;paypal&quot;&gt;&lt;a href=&quot;#&quot;&gt;&lt;\/a&gt;&lt;\/li&gt;\r\n&lt;li class=&quot;mastercard&quot;&gt;&lt;a href=&quot;#&quot;&gt;&lt;\/a&gt;&lt;\/li&gt;\r\n&lt;li class=&quot;discover&quot;&gt;&lt;a href=&quot;#&quot;&gt;&lt;\/a&gt;&lt;\/li&gt;\r\n&lt;li class=&quot;americanexpress&quot;&gt;&lt;a href=&quot;#&quot;&gt;&lt;\/a&gt;&lt;\/li&gt;\r\n&lt;\/ul&gt;\r\n&lt;\/div&gt;\r\n&lt;\/div&gt;"}},"status":"1"}');
INSERT INTO `oc_module` (module_id,name,code,setting) VALUES (39,'Footer-Newsletter-Text ','html','{"name":"Footer-Newsletter-Text ","module_description":{"1":{"title":"","description":"&lt;p&gt;&lt;span style=&quot;color: rgb(85, 85, 85); font-family: &amp;quot;Open Sans&amp;quot;, Helvetica, sans-serif; font-size: 14px;&quot;&gt;Contrary to popular belief, Lorem Ipsum Latin Latin from.&lt;\/span&gt;&lt;br&gt;&lt;\/p&gt;"}},"status":"1"}');
INSERT INTO `oc_module` (module_id,name,code,setting) VALUES (40,'FooterRight-Contact-CMS ','html','{"name":"FooterRight-Contact-CMS ","module_description":{"1":{"title":"","description":"&lt;div id=&quot;contact&quot; class=&quot;col-sm-3 column&quot;&gt;\r\n&lt;h5 class=&quot;&quot;&gt;company info&lt;\/h5&gt;\r\n&lt;ul&gt;\r\n&lt;li&gt;&lt;div class=&quot;address&quot;&gt;&lt;i class=&quot;fa fa-map-marker&quot;&gt; &lt;\/i&gt;&lt;div class=&quot;address_content&quot;&gt;&lt;div class=&quot;contact_address&quot;&gt;507-Union Trade Centre, Beside Apple Hospital, Udhana Darwaja, Surat&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;\/li&gt;\r\n&lt;li&gt;&lt;div class=&quot;phone&quot;&gt;&lt;i class=&quot;fa fa-mobile&quot;&gt; &lt;\/i&gt;&lt;div class=&quot;contact_phone&quot;&gt;+91 8866888222&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;\/li&gt;\r\n&lt;li&gt;\r\n&lt;div class=&quot;email&quot;&gt;&lt;i class=&quot;fa fa-envelope &quot;&gt; &lt;\/i&gt;&lt;div class=&quot;contact_email&quot;&gt;&lt;a target=&quot;_blank&quot; href=&quot;#&quot;&gt;@templatemela.com&lt;\/a&gt;&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;\/li&gt;\r\n&lt;\/ul&gt;\r\n&lt;\/div&gt;"}},"status":"1"}');
INSERT INTO `oc_module` (module_id,name,code,setting) VALUES (41,'FooterTop-Assurance-CMS ','html','{"name":"FooterTop-Assurance-CMS ","module_description":{"1":{"title":"","description":"&lt;div class=&quot;footertop-cms container&quot;&gt;\r\n&lt;div class=&quot;row&quot;&gt;\r\n&lt;div class=&quot;footerblock1 footerblock&quot;&gt;\r\n&lt;div class=&quot;title&quot;&gt;special gift cards&lt;\/div&gt;\r\n&lt;div class=&quot;subtitle&quot;&gt;give the perfect gift&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;div class=&quot;footerblock2 footerblock&quot;&gt;\r\n&lt;div class=&quot;title&quot;&gt;free shipping&lt;\/div&gt;\r\n&lt;div class=&quot;subtitle&quot;&gt;on orders over $99&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;div class=&quot;footerblock3 footerblock&quot;&gt;&lt;div class=&quot;title&quot;&gt;order online&lt;\/div&gt;\r\n&lt;div class=&quot;subtitle&quot;&gt;hours : 8am - 11pm&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;div class=&quot;footerblock4 footerblock&quot;&gt;&lt;div class=&quot;title&quot;&gt;shop and save&lt;\/div&gt;\r\n&lt;div class=&quot;subtitle&quot;&gt;for all spices &amp;amp; herbs&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;\/div&gt;"}},"status":"1"}');
INSERT INTO `oc_module` (module_id,name,code,setting) VALUES (43,'Sidebar Latest','latest','{"name":"Sidebar Latest","limit":"4","width":"75","height":"100","status":"1"}');
INSERT INTO `oc_module` (module_id,name,code,setting) VALUES (44,'Sidebar Special','special','{"name":"Sidebar Special","limit":"4","width":"75","height":"100","status":"1"}');
INSERT INTO `oc_module` (module_id,name,code,setting) VALUES (45,'Category Product Tab','category_tab','{"name":"Category Product Tab","heading":"Top Category","category":"","product_category":["33","29","28"],"category_limit":"3","product_limit":"8","width":"218","height":"286","status":"1"}');
INSERT INTO `oc_module` (module_id,name,code,setting) VALUES (46,'HomePage Product Tabs','megnortabs','{"name":"HomePage Product Tabs","limit":"10","width":"216","height":"284","status":"1"}');
INSERT INTO `oc_module` (module_id,name,code,setting) VALUES (47,'Home Page Slideshow','slideshow','{"name":"Home Page Slideshow","banner_id":"7","width":"914","height":"420","status":"1"}');
INSERT INTO `oc_module` (module_id,name,code,setting) VALUES (49,'Home Page Manufacturers','banner','{"name":"Home Page Manufacturers","banner_id":"8","width":"112","height":"112","status":"1"}');
INSERT INTO `oc_module` (module_id,name,code,setting) VALUES (52,'Home Page Manufacturers','carousel','{"name":"Home Page Manufacturers","banner_id":"8","width":"112","height":"112","status":"1"}');
INSERT INTO `oc_module` (module_id,name,code,setting) VALUES (53,'Rightbanner1','banner','{"name":"Rightbanner1","banner_id":"10","width":"236","height":"350","status":"1"}');
INSERT INTO `oc_module` (module_id,name,code,setting) VALUES (54,'Column Right Testimonial CMS','html','{"name":"Column Right Testimonial CMS","module_description":{"1":{"title":"","description":"&lt;div class=&quot;testimonials&quot; id=&quot;testimonial&quot;&gt;\r\n&lt;div class=&quot;homepage-testimonial-inner&quot;&gt;\r\n&lt;div class=&quot;testimonial_inner&quot;&gt;&lt;div class=&quot;box-heading&quot;&gt;Testimonial&lt;\/div&gt;\r\n&lt;div class=&quot;homepage-testimonials-inner products box-content&quot;&gt;\r\n&lt;div class=&quot;customNavigation&quot;&gt;&lt;a class=&quot;btn prev&quot;&gt;&lt;\/a&gt;&lt;a class=&quot;btn next&quot;&gt;&lt;\/a&gt;&lt;\/div&gt;\r\n&lt;div class=&quot;products product-carousel&quot; id=&quot;testimonial-carousel&quot;&gt;\r\n&lt;div class=&quot;slider-item&quot;&gt;\r\n&lt;div class=&quot;peoplesay-block&quot;&gt;\r\n&lt;div class=&quot;test-image&quot;&gt;\r\n&lt;img src=&quot;image\/catalog\/user.jpg&quot; alt=&quot;&quot;&gt;&lt;\/div&gt;\r\n&lt;div class=&quot;testi-details&quot;&gt;&lt;a href=&quot;#&quot;&gt;Quia Voluptas&lt;\/a&gt;&lt;\/div&gt;\r\n&lt;div class=&quot;designation&quot;&gt;&lt;a href=&quot;#&quot;&gt; view tweet&lt;\/a&gt;&lt;\/div&gt;\r\n&lt;div class=&quot;test-content&quot;&gt;&lt;div class=&quot;quote-img&quot;&gt;&lt;\/div&gt;\r\n&lt;div class=&quot;test-desc&quot;&gt;&lt;p&gt;Maecenas nec fringilla felis Nulla ultrices pulvinar magna in iaculis.&lt;\/p&gt;\r\n&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;div class=&quot;slider-item&quot;&gt;\r\n&lt;div class=&quot;peoplesay-block&quot;&gt;\r\n&lt;div class=&quot;test-image&quot;&gt;\r\n&lt;img src=&quot;image\/catalog\/user.jpg&quot; alt=&quot;&quot;&gt;&lt;\/div&gt;\r\n&lt;div class=&quot;testi-details&quot;&gt;&lt;a href=&quot;#&quot;&gt;Mrtin willms&lt;\/a&gt;&lt;\/div&gt;\r\n&lt;div class=&quot;designation&quot;&gt;&lt;a href=&quot;#&quot;&gt; view tweet&lt;\/a&gt;&lt;\/div&gt;\r\n&lt;div class=&quot;test-content&quot;&gt;&lt;div class=&quot;quote-img&quot;&gt;&lt;\/div&gt;\r\n&lt;div class=&quot;test-desc&quot;&gt;&lt;p&gt;Ipsum Maecenas nec fringilla felis Nulla ultrices pulvinar magna in iaculis.&lt;\/p&gt;\r\n&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;div class=&quot;slider-item&quot;&gt;\r\n&lt;div class=&quot;peoplesay-block&quot;&gt;\r\n&lt;div class=&quot;test-image&quot;&gt;\r\n&lt;img src=&quot;image\/catalog\/user.jpg&quot; alt=&quot;&quot;&gt;&lt;\/div&gt;\r\n&lt;div class=&quot;testi-details&quot;&gt;&lt;a href=&quot;#&quot;&gt;john roy&lt;\/a&gt;&lt;\/div&gt;\r\n&lt;div class=&quot;designation&quot;&gt;&lt;a href=&quot;#&quot;&gt; view tweet&lt;\/a&gt;&lt;\/div&gt;\r\n&lt;div class=&quot;test-content&quot;&gt;&lt;div class=&quot;quote-img&quot;&gt;&lt;\/div&gt;\r\n&lt;div class=&quot;test-desc&quot;&gt;&lt;p&gt;Lorem Ipsum has been the industrys standard with dumpty Text.&lt;\/p&gt;\r\n&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;div class=&quot;testimonial_default_width&quot; style=&quot;display: none; visibility: hidden;&quot;&gt;&amp;nbsp;&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;\/div&gt;"}},"status":"1"}');
INSERT INTO `oc_module` (module_id,name,code,setting) VALUES (55,'Column-right Service Banner CMS','html','{"name":"Column-right Service Banner CMS","module_description":{"1":{"title":"","description":"&lt;div class=&quot;service-banner&quot;&gt;\r\n&lt;div class=&quot;box-heading&quot;&gt;Our Services&lt;\/div&gt;\r\n&lt;div class=&quot;box-content&quot;&gt;\r\n&lt;div class=&quot;ser-banner banner1&quot;&gt;\r\n&lt;a href=&quot;#&quot;&gt;\r\n&lt;div class=&quot;ser-text1&quot;&gt;Price&lt;\/div&gt;\r\n&lt;div class=&quot;ser-text2&quot;&gt;Delightful&lt;\/div&gt;\r\n&lt;div class=&quot;ser-text3&quot;&gt;PageMaker sheac&lt;\/div&gt;\r\n&lt;div class=&quot;round_img&quot;&gt;\r\n&lt;img src=&quot;image\/catalog\/icon_6.png&quot; alt=&quot;&quot;&gt;&lt;\/div&gt;\r\n&lt;\/a&gt;&lt;\/div&gt;\r\n&lt;div class=&quot;ser-banner banner2&quot;&gt;\r\n&lt;a href=&quot;index.php?route=product\/category&amp;amp;path=20&quot;&gt;\r\n&lt;div class=&quot;ser-text1&quot;&gt;Guides&lt;\/div&gt;\r\n&lt;div class=&quot;ser-text2&quot;&gt;Shopping&lt;\/div&gt;\r\n&lt;div class=&quot;ser-text3&quot;&gt;Dheact acthat&lt;\/div&gt;\r\n&lt;div class=&quot;round_img&quot;&gt;\r\n&lt;img src=&quot;image\/catalog\/icon_5.png&quot; alt=&quot;&quot;&gt;&lt;\/div&gt;\r\n&lt;\/a&gt;&lt;\/div&gt;\r\n&lt;div class=&quot;ser-banner banner3&quot;&gt;\r\n&lt;a href=&quot;index.php?route=account\/login&quot;&gt;\r\n&lt;div class=&quot;ser-text1&quot;&gt;Login&lt;\/div&gt;\r\n&lt;div class=&quot;ser-text2&quot;&gt;Checkout&lt;\/div&gt;\r\n&lt;div class=&quot;ser-text3&quot;&gt;All payment service&lt;\/div&gt;\r\n&lt;div class=&quot;round_img&quot;&gt;\r\n&lt;img src=&quot;image\/catalog\/icon_4.png&quot; alt=&quot;&quot;&gt;&lt;\/div&gt;\r\n&lt;\/a&gt;&lt;\/div&gt;\r\n&lt;div class=&quot;ser-banner banner4&quot;&gt;\r\n&lt;a href=&quot;#&quot;&gt;\r\n&lt;div class=&quot;ser-text1&quot;&gt;Free&lt;\/div&gt;\r\n&lt;div class=&quot;ser-text2&quot;&gt;Delivery&lt;\/div&gt;\r\n&lt;div class=&quot;ser-text3&quot;&gt;Mobile Application&lt;\/div&gt;\r\n&lt;div class=&quot;round_img&quot;&gt;\r\n&lt;img src=&quot;image\/catalog\/icon_3.png&quot; alt=&quot;&quot;&gt;&lt;\/div&gt;\r\n&lt;\/a&gt;&lt;\/div&gt;\r\n&lt;div class=&quot;ser-banner banner5&quot;&gt;\r\n&lt;a href=&quot;OPC2\/index.php?route=account\/register&quot;&gt;\r\n&lt;div class=&quot;ser-text1&quot;&gt;Register&lt;\/div&gt;\r\n&lt;div class=&quot;ser-text2&quot;&gt;My Details&lt;\/div&gt;\r\n&lt;div class=&quot;ser-text3&quot;&gt;Your Bank Account&lt;\/div&gt;\r\n&lt;div class=&quot;round_img&quot;&gt;\r\n&lt;img src=&quot;image\/catalog\/icon_2.png&quot; alt=&quot;&quot;&gt;&lt;\/div&gt;\r\n&lt;\/a&gt;&lt;\/div&gt;\r\n&lt;div class=&quot;ser-banner banner6&quot;&gt;\r\n&lt;a href=&quot;#&quot;&gt;\r\n&lt;div class=&quot;ser-text1&quot;&gt;Mobile&lt;\/div&gt;\r\n&lt;div class=&quot;ser-text2&quot;&gt;Marketing&lt;\/div&gt;\r\n&lt;div class=&quot;ser-text3&quot;&gt;PageMaker she&lt;\/div&gt;\r\n&lt;div class=&quot;round_img&quot;&gt;\r\n&lt;img src=&quot;image\/catalog\/icon_1.png&quot; alt=&quot;&quot;&gt;&lt;\/div&gt;\r\n&lt;\/a&gt;&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;\/div&gt;"}},"status":"1"}');
INSERT INTO `oc_module` (module_id,name,code,setting) VALUES (56,'HomePage Banner CMS','html','{"name":"HomePage Banner CMS","module_description":{"1":{"title":"","description":"&lt;div class=&quot;subbanner-cms2&quot;&gt;\r\n&lt;div class=&quot;sub-heading row&quot;&gt;Catchy offers&lt;\/div&gt;\r\n&lt;div class=&quot;subbanner-inner&quot;&gt; \r\n&lt;div class=&quot;subbannerpart1&quot;&gt;\r\n&lt;div class=&quot;subbanner-one&quot;&gt; \r\n&lt;div class=&quot;content-inner&quot;&gt; \r\n&lt;a href=&quot;#&quot;&gt;&lt;img src=&quot;image\/catalog\/small_banner2.jpg&quot; alt=&quot;&quot;&gt;&lt;\/a&gt; \r\n&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;div class=&quot;subbannerpart2&quot;&gt; \r\n&lt;div class=&quot;subbanner-two&quot;&gt; \r\n&lt;div class=&quot;content-inner&quot;&gt; \r\n&lt;div class=&quot;img1&quot;&gt; \r\n&lt;a href=&quot;#&quot;&gt;&lt;img src=&quot;image\/catalog\/small_banner3.jpg&quot; alt=&quot;&quot;&gt;&lt;\/a&gt; \r\n&lt;\/div&gt;\r\n&lt;div class=&quot;img2&quot;&gt;\r\n&lt;a href=&quot;#&quot;&gt;&lt;img src=&quot;image\/catalog\/small_banner4.jpg&quot; alt=&quot;&quot;&gt;&lt;\/a&gt; \r\n&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;\/div&gt;"}},"status":"1"}');
INSERT INTO `oc_module` (module_id,name,code,setting) VALUES (57,'Sidebar Featured','featured','{"name":"Sidebar Featured","product_name":"","product":["42","47","28","41"],"limit":"4","width":"75","height":"100","status":"1"}');
INSERT INTO `oc_module` (module_id,name,code,setting) VALUES (58,'HomePage Bestseller','bestseller','{"name":"HomePage Bestseller","limit":"10","width":"218","height":"286","status":"1"}');
INSERT INTO `oc_module` (module_id,name,code,setting) VALUES (60,'Special Products','special','{"name":"Special Products","limit":"4","width":"75","height":"100","status":"1"}');
INSERT INTO `oc_module` (module_id,name,code,setting) VALUES (61,'Rightbanner2','banner','{"name":"Rightbanner2","banner_id":"11","width":"236","height":"342","status":"1"}');
INSERT INTO `oc_module` (module_id,name,code,setting) VALUES (62,'Manufacturers','banner','{"name":"Manufacturers","banner_id":"8","width":"112","height":"112","status":"1"}');
INSERT INTO `oc_module` (module_id,name,code,setting) VALUES (63,'Sidebar Bestseller','bestseller','{"name":"Sidebar Bestseller","limit":"3","width":"75","height":"100","status":"1"}');


INSERT INTO `oc_setting` (setting_id,store_id,code,`key`,`value`,serialized) VALUES (381,0,'theme_default','theme_default_directory','OPC080192_2',0);
INSERT INTO `oc_setting` (setting_id,store_id,code,`key`,`value`,serialized) VALUES (382,0,'theme_default','theme_default_status','1',0);
INSERT INTO `oc_setting` (setting_id,store_id,code,`key`,`value`,serialized) VALUES (383,0,'theme_default','theme_default_product_limit','12',0);
INSERT INTO `oc_setting` (setting_id,store_id,code,`key`,`value`,serialized) VALUES (384,0,'theme_default','theme_default_product_description_length','200',0);
INSERT INTO `oc_setting` (setting_id,store_id,code,`key`,`value`,serialized) VALUES (385,0,'theme_default','theme_default_image_category_width','914',0);
INSERT INTO `oc_setting` (setting_id,store_id,code,`key`,`value`,serialized) VALUES (386,0,'theme_default','theme_default_image_category_height','154',0);
INSERT INTO `oc_setting` (setting_id,store_id,code,`key`,`value`,serialized) VALUES (387,0,'theme_default','theme_default_image_thumb_width','456',0);
INSERT INTO `oc_setting` (setting_id,store_id,code,`key`,`value`,serialized) VALUES (388,0,'theme_default','theme_default_image_thumb_height','600',0);
INSERT INTO `oc_setting` (setting_id,store_id,code,`key`,`value`,serialized) VALUES (389,0,'theme_default','theme_default_image_popup_width','760',0);
INSERT INTO `oc_setting` (setting_id,store_id,code,`key`,`value`,serialized) VALUES (390,0,'theme_default','theme_default_image_popup_height','1000',0);
INSERT INTO `oc_setting` (setting_id,store_id,code,`key`,`value`,serialized) VALUES (391,0,'theme_default','theme_default_image_product_width','218',0);
INSERT INTO `oc_setting` (setting_id,store_id,code,`key`,`value`,serialized) VALUES (392,0,'theme_default','theme_default_image_product_height','286',0);
INSERT INTO `oc_setting` (setting_id,store_id,code,`key`,`value`,serialized) VALUES (393,0,'theme_default','theme_default_image_additional_width','456',0);
INSERT INTO `oc_setting` (setting_id,store_id,code,`key`,`value`,serialized) VALUES (394,0,'theme_default','theme_default_image_additional_height','600',0);
INSERT INTO `oc_setting` (setting_id,store_id,code,`key`,`value`,serialized) VALUES (395,0,'theme_default','theme_default_image_related_width','218',0);
INSERT INTO `oc_setting` (setting_id,store_id,code,`key`,`value`,serialized) VALUES (396,0,'theme_default','theme_default_image_related_height','286',0);
INSERT INTO `oc_setting` (setting_id,store_id,code,`key`,`value`,serialized) VALUES (397,0,'theme_default','theme_default_image_compare_width','57',0);
INSERT INTO `oc_setting` (setting_id,store_id,code,`key`,`value`,serialized) VALUES (398,0,'theme_default','theme_default_image_compare_height','75',0);
INSERT INTO `oc_setting` (setting_id,store_id,code,`key`,`value`,serialized) VALUES (399,0,'theme_default','theme_default_image_wishlist_width','57',0);
INSERT INTO `oc_setting` (setting_id,store_id,code,`key`,`value`,serialized) VALUES (400,0,'theme_default','theme_default_image_wishlist_height','75',0);
INSERT INTO `oc_setting` (setting_id,store_id,code,`key`,`value`,serialized) VALUES (401,0,'theme_default','theme_default_image_cart_width','57',0);
INSERT INTO `oc_setting` (setting_id,store_id,code,`key`,`value`,serialized) VALUES (402,0,'theme_default','theme_default_image_cart_height','75',0);
INSERT INTO `oc_setting` (setting_id,store_id,code,`key`,`value`,serialized) VALUES (403,0,'theme_default','theme_default_image_location_width','268',0);
INSERT INTO `oc_setting` (setting_id,store_id,code,`key`,`value`,serialized) VALUES (404,0,'theme_default','theme_default_image_location_height','50',0);


truncate table oc_layout_module;
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (215,5,'megnorcategory','column_left',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (216,5,'special.44','column_left',1);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (217,5,'search_suggestion','content_top',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (218,5,'html.41','footertop',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (219,5,'html.38','footerbottom',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (220,5,'html.40','footerright',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (221,5,'html.39','footernewstext',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (222,5,'html.35','headertop',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (223,5,'html.36','headertop',1);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (224,5,'html.32','headertopleft',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (225,2,'megnorcategory','column_left',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (226,2,'latest.43','column_left',1);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (227,2,'special.44','column_left',2);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (228,2,'search_suggestion','content_top',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (229,2,'html.41','footertop',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (230,2,'html.38','footerbottom',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (231,2,'html.40','footerright',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (232,2,'html.39','footernewstext',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (233,2,'html.35','headertop',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (234,2,'html.36','headertop',1);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (235,2,'html.32','headertopleft',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (236,13,'megnorcategory','column_left',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (237,13,'latest.43','column_left',1);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (238,13,'special.44','column_left',2);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (239,13,'information','column_left',3);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (240,13,'search_suggestion','content_top',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (241,13,'html.41','footertop',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (242,13,'html.38','footerbottom',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (243,13,'html.40','footerright',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (244,13,'html.39','footernewstext',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (245,13,'html.35','headertop',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (246,13,'html.36','headertop',1);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (247,13,'html.32','headertopleft',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (248,9,'megnorcategory','column_left',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (249,9,'information','column_left',1);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (250,9,'search_suggestion','content_top',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (251,9,'html.41','footertop',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (252,9,'html.38','footerbottom',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (253,9,'html.40','footerright',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (254,9,'html.39','footernewstext',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (255,9,'html.35','headertop',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (256,9,'html.36','headertop',1);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (257,9,'html.32','headertopleft',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (288,10,'search_suggestion','content_top',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (289,10,'html.41','footertop',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (290,10,'html.38','footerbottom',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (291,10,'html.39','footernewstext',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (292,10,'html.40','footerright',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (293,10,'account','column_right',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (294,10,'information','column_right',1);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (295,6,'search_suggestion','content_top',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (296,6,'html.41','footertop',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (297,6,'html.38','footerbottom',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (298,6,'html.39','footernewstext',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (299,6,'html.40','footerright',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (300,6,'account','column_right',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (301,6,'information','column_right',1);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (334,7,'search_suggestion','content_top',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (335,7,'html.41','footertop',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (336,7,'html.38','footerbottom',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (337,7,'html.39','footernewstext',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (338,7,'html.40','footerright',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (339,7,'information','column_right',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (340,7,'latest.43','column_right',1);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (341,12,'search_suggestion','content_top',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (342,12,'html.41','footertop',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (343,12,'html.38','footerbottom',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (344,12,'html.39','footernewstext',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (345,12,'html.40','footerright',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (346,12,'information','column_right',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (347,12,'latest.43','column_right',1);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (360,3,'search_suggestion','content_top',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (361,3,'category','column_right',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (362,3,'account','column_right',1);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (364,3,'banner.61','column_right',3);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (365,8,'search_suggestion','content_top',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (366,8,'html.41','footertop',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (367,8,'html.38','footerbottom',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (368,8,'html.39','footernewstext',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (369,8,'html.40','footerright',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (370,8,'information','column_right',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (372,4,'account','content_top',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (373,4,'search_suggestion','content_top',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (374,4,'account','content_top',1);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (375,4,'html.41','footertop',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (376,4,'html.38','footerbottom',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (377,4,'html.39','footernewstext',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (378,4,'html.40','footerright',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (379,4,'account','footerright',1);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (380,4,'information','column_right',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (381,4,'latest.43','column_right',1);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (382,11,'search_suggestion','content_top',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (383,11,'html.41','footertop',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (384,11,'html.38','footerbottom',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (385,11,'html.39','footernewstext',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (386,11,'html.40','footerright',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (387,11,'information','column_right',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (388,11,'special.44','column_right',1);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (428,1,'search_suggestion','content_top',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (429,1,'slideshow.47','content_top',1);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (430,1,'banner.31','content_top',2);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (431,1,'category_tab.45','content_top',3);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (432,1,'featured.28','content_top',4);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (433,1,'html.56','content_top',5);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (434,1,'html.37','content_top',6);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (435,1,'bestseller.58','content_top',7);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (436,1,'banner.49','content_top',8);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (437,1,'html.41','footertop',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (438,1,'html.38','footerbottom',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (439,1,'html.39','footernewstext',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (440,1,'html.40','footerright',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (441,1,'newsletters','footerright',1);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (442,1,'html.55','column_right',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (443,1,'banner.53','column_right',1);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (444,1,'latest.43','column_right',2);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (445,1,'banner.61','column_right',3);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (446,1,'special.44','column_right',4);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (447,1,'html.54','column_right',5);

truncate table oc_module;


INSERT INTO `oc_module` (module_id,name,code,setting) VALUES (27,'Home Page','slideshow','{"name":"Home Page","banner_id":"7","width":"1140","height":"380","status":"1"}');
INSERT INTO `oc_module` (module_id,name,code,setting) VALUES (28,'Home Page','featured','{"name":"Home Page","product_name":"","product":["43","40","42","30","41","47"],"limit":"7","width":"218","height":"286","status":"1"}');
INSERT INTO `oc_module` (module_id,name,code,setting) VALUES (31,'SubBanner','banner','{"name":"SubBanner","banner_id":"6","width":"914","height":"60","status":"1"}');
INSERT INTO `oc_module` (module_id,name,code,setting) VALUES (32,'HeaderTop-Offer-CMS','html','{"name":"HeaderTop-Offer-CMS","module_description":{"1":{"title":"","description":"&lt;p&gt;&lt;br&gt;&lt;\/p&gt;"}},"status":"1"}');
INSERT INTO `oc_module` (module_id,name,code,setting) VALUES (33,'HomePage-Subbanner2-CMS','html','{"name":"HomePage-Subbanner2-CMS","module_description":{"1":{"title":"","description":"&lt;p&gt;&lt;br&gt;&lt;\/p&gt;"}},"status":"1"}');
INSERT INTO `oc_module` (module_id,name,code,setting) VALUES (34,'HomePage-Subbanner3-CMS ','html','{"name":"HomePage-Subbanner3-CMS ","module_description":{"1":{"title":"","description":"&lt;p&gt;&lt;br&gt;&lt;\/p&gt;"}},"status":"1"}');
INSERT INTO `oc_module` (module_id,name,code,setting) VALUES (35,'HeaderTopLeft-Shipping-CMS ','html','{"name":"HeaderTopLeft-Shipping-CMS ","module_description":{"1":{"title":"","description":"&lt;p&gt;&lt;br&gt;&lt;\/p&gt;"}},"status":"1"}');
INSERT INTO `oc_module` (module_id,name,code,setting) VALUES (36,' HeaderTopRight-Contact-CMS','html','{"name":" HeaderTopRight-Contact-CMS","module_description":{"1":{"title":"","description":"&lt;p&gt;&lt;br&gt;&lt;\/p&gt;"}},"status":"1"}');
INSERT INTO `oc_module` (module_id,name,code,setting) VALUES (37,'HomePage-Category-CMS','html','{"name":"HomePage-Category-CMS","module_description":{"1":{"title":"","description":"&lt;div class=&quot;category-cms&quot;&gt; \r\n&lt;div class=&quot;category-container&quot;&gt; \r\n&lt;div class=&quot;category-row&quot;&gt; \r\n&lt;div class=&quot;categoryblock1 categoryblock&quot;&gt; \r\n&lt;div class=&quot;category&quot;&gt; \r\n&lt;div class=&quot;cat-desc&quot;&gt; \r\n&lt;div class=&quot;cate-heading&quot;&gt;&lt;a href=&quot;#&quot;&gt;mobile&lt;\/a&gt;&lt;\/div&gt;\r\n&lt;ul class=&quot;subcats&quot;&gt;\r\n&lt;li&gt;&lt;a href=&quot;#&quot;&gt;smart&lt;\/a&gt;&lt;\/li&gt;\r\n&lt;li&gt;&lt;a href=&quot;#&quot;&gt;comfortable&lt;\/a&gt;&lt;\/li&gt;\r\n&lt;li&gt;&lt;a href=&quot;#&quot;&gt;stylist&lt;\/a&gt;&lt;\/li&gt;\r\n&lt;li&gt;&lt;a href=&quot;#&quot;&gt;fomforta&lt;\/a&gt;&lt;\/li&gt;\r\n&lt;\/ul&gt;\r\n&lt;\/div&gt;\r\n&lt;div class=&quot;image&quot;&gt;\r\n&lt;a href=&quot;#&quot;&gt;&lt;img src=&quot;image\/catalog\/01.jpg&quot; alt=&quot;&quot; class=&quot;img-responsive&quot;&gt;&lt;\/a&gt;&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;div class=&quot;categoryblock2 categoryblock&quot;&gt; \r\n&lt;div class=&quot;category&quot;&gt; \r\n&lt;div class=&quot;cat-desc&quot;&gt; \r\n&lt;div class=&quot;cate-heading&quot;&gt;&lt;a href=&quot;#&quot;&gt;accessories&lt;\/a&gt;&lt;\/div&gt;\r\n&lt;ul class=&quot;subcats&quot;&gt;\r\n&lt;li&gt;&lt;a href=&quot;#&quot;&gt;chorme&lt;\/a&gt;&lt;\/li&gt;\r\n&lt;li&gt;&lt;a href=&quot;#&quot;&gt;firefox add&lt;\/a&gt;&lt;\/li&gt;\r\n&lt;li&gt;&lt;a href=&quot;#&quot;&gt;nodeJS&lt;\/a&gt;&lt;\/li&gt;\r\n&lt;li&gt;&lt;a href=&quot;#&quot;&gt;tax package&lt;\/a&gt;&lt;\/li&gt;\r\n&lt;\/ul&gt;\r\n&lt;\/div&gt;\r\n&lt;div class=&quot;image&quot;&gt;\r\n&lt;a href=&quot;#&quot;&gt;&lt;img src=&quot;image\/catalog\/02.jpg&quot; alt=&quot;&quot; class=&quot;img-responsive&quot;&gt;&lt;\/a&gt;&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;div class=&quot;categoryblock3 categoryblock&quot;&gt; \r\n&lt;div class=&quot;category&quot;&gt; \r\n&lt;div class=&quot;cat-desc&quot;&gt; \r\n&lt;div class=&quot;cate-heading&quot;&gt;&lt;a href=&quot;#&quot;&gt;furniture&lt;\/a&gt;&lt;\/div&gt;\r\n&lt;ul class=&quot;subcats&quot;&gt;\r\n&lt;li&gt;&lt;a href=&quot;#&quot;&gt;keyword Prote&lt;\/a&gt;&lt;\/li&gt;\r\n&lt;li&gt;&lt;a href=&quot;#&quot;&gt;laptop bags&lt;\/a&gt;&lt;\/li&gt;\r\n&lt;li&gt;&lt;a href=&quot;#&quot;&gt;latest model&lt;\/a&gt;&lt;\/li&gt;\r\n&lt;li&gt;&lt;a href=&quot;#&quot;&gt;eyword&lt;\/a&gt;&lt;\/li&gt;\r\n&lt;\/ul&gt;\r\n&lt;\/div&gt;\r\n&lt;div class=&quot;image&quot;&gt;\r\n&lt;a href=&quot;#&quot;&gt;&lt;img src=&quot;image\/catalog\/03.jpg&quot; alt=&quot;&quot; class=&quot;img-responsive&quot;&gt;&lt;\/a&gt;&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;div class=&quot;categoryblock4 categoryblock&quot;&gt; \r\n&lt;div class=&quot;category&quot;&gt; \r\n&lt;div class=&quot;cat-desc&quot;&gt; \r\n&lt;div class=&quot;cate-heading&quot;&gt;&lt;a href=&quot;#&quot;&gt;Kitchen&lt;\/a&gt;&lt;\/div&gt;\r\n&lt;ul class=&quot;subcats&quot;&gt;\r\n&lt;li&gt;&lt;a href=&quot;#&quot;&gt;microwave&lt;\/a&gt;&lt;\/li&gt;\r\n&lt;li&gt;&lt;a href=&quot;#&quot;&gt;cooktops&lt;\/a&gt;&lt;\/li&gt;\r\n&lt;li&gt;&lt;a href=&quot;#&quot;&gt;juicer Grinders&lt;\/a&gt;&lt;\/li&gt;\r\n&lt;li&gt;&lt;a href=&quot;#&quot;&gt;Electric cookers&lt;\/a&gt;&lt;\/li&gt;\r\n&lt;\/ul&gt;\r\n&lt;\/div&gt;\r\n&lt;div class=&quot;image&quot;&gt;\r\n&lt;a href=&quot;#&quot;&gt;&lt;img src=&quot;image\/catalog\/04.jpg&quot; alt=&quot;&quot; class=&quot;img-responsive&quot;&gt;&lt;\/a&gt;&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;div class=&quot;categoryblock5 categoryblock&quot;&gt; \r\n&lt;div class=&quot;category&quot;&gt; \r\n&lt;div class=&quot;cat-desc&quot;&gt; \r\n&lt;div class=&quot;cate-heading&quot;&gt;&lt;a href=&quot;#&quot;&gt;computers&lt;\/a&gt;&lt;\/div&gt;\r\n&lt;ul class=&quot;subcats&quot;&gt;\r\n&lt;li&gt;&lt;a href=&quot;#&quot;&gt;laptop&lt;\/a&gt;&lt;\/li&gt;\r\n&lt;li&gt;&lt;a href=&quot;#&quot;&gt;computer&lt;\/a&gt;&lt;\/li&gt;\r\n&lt;li&gt;&lt;a href=&quot;#&quot;&gt;network&lt;\/a&gt;&lt;\/li&gt;\r\n&lt;li&gt;&lt;a href=&quot;#&quot;&gt;computer&lt;\/a&gt;&lt;\/li&gt;\r\n&lt;\/ul&gt;\r\n&lt;\/div&gt;\r\n&lt;div class=&quot;image&quot;&gt;\r\n&lt;a href=&quot;#&quot;&gt;&lt;img src=&quot;image\/catalog\/05.jpg&quot; alt=&quot;&quot; class=&quot;img-responsive&quot;&gt;&lt;\/a&gt;&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;div class=&quot;categoryblock6 categoryblock&quot;&gt; \r\n&lt;div class=&quot;category&quot;&gt; \r\n&lt;div class=&quot;cat-desc&quot;&gt; \r\n&lt;div class=&quot;cate-heading&quot;&gt;&lt;a href=&quot;#&quot;&gt;cosmetics&lt;\/a&gt;&lt;\/div&gt;\r\n&lt;ul class=&quot;subcats&quot;&gt;\r\n&lt;li&gt;&lt;a href=&quot;#&quot;&gt;skin care&lt;\/a&gt;&lt;\/li&gt;\r\n&lt;li&gt;&lt;a href=&quot;#&quot;&gt;beauty products&lt;\/a&gt;&lt;\/li&gt;\r\n&lt;li&gt;&lt;a href=&quot;#&quot;&gt;no side effects&lt;\/a&gt;&lt;\/li&gt;\r\n&lt;li&gt;&lt;a href=&quot;#&quot;&gt;products&lt;\/a&gt;&lt;\/li&gt;\r\n&lt;\/ul&gt;\r\n&lt;\/div&gt;\r\n&lt;div class=&quot;image&quot;&gt;\r\n&lt;a href=&quot;#&quot;&gt;&lt;img src=&quot;image\/catalog\/06.jpg&quot; alt=&quot;&quot; class=&quot;img-responsive&quot;&gt;&lt;\/a&gt;&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;\/div&gt;"}},"status":"1"}');
INSERT INTO `oc_module` (module_id,name,code,setting) VALUES (38,'Footer-Bottom-CMS ','html','{"name":"Footer-Bottom-CMS ","module_description":{"1":{"title":"","description":"&lt;div class=&quot;footerbottom-cms&quot;&gt;\r\n&lt;div class=&quot;social-cms&quot;&gt; \r\n&lt;ul class=&quot;social&quot;&gt;\r\n&lt;li class=&quot;facebook&quot;&gt;&lt;a href=&quot;#&quot;&gt;&lt;\/a&gt;&lt;\/li&gt;\r\n&lt;li class=&quot;twitter&quot;&gt;&lt;a href=&quot;#&quot;&gt;&lt;\/a&gt;&lt;\/li&gt;\r\n&lt;li class=&quot;gplus&quot;&gt;&lt;a href=&quot;#&quot;&gt;&lt;\/a&gt;&lt;\/li&gt;\r\n&lt;li class=&quot;linkedin&quot;&gt;&lt;a href=&quot;#&quot;&gt;&lt;\/a&gt;&lt;\/li&gt;\r\n&lt;\/ul&gt;\r\n&lt;\/div&gt;\r\n&lt;div class=&quot;app-cms&quot;&gt;\r\n&lt;ul class=&quot;app&quot;&gt;\r\n&lt;li class=&quot;playstore&quot;&gt;&lt;a href=&quot;#&quot;&gt;&lt;\/a&gt;&lt;\/li&gt;\r\n&lt;li class=&quot;appstore&quot;&gt;&lt;a href=&quot;#&quot;&gt;&lt;\/a&gt;&lt;\/li&gt;\r\n&lt;li class=&quot;windowsstore&quot;&gt;&lt;a href=&quot;#&quot;&gt;&lt;\/a&gt;&lt;\/li&gt;\r\n&lt;\/ul&gt;\r\n&lt;\/div&gt;\r\n&lt;div class=&quot;payment-cms&quot;&gt; \r\n&lt;ul class=&quot;payment&quot;&gt;\r\n&lt;li class=&quot;visa&quot;&gt;&lt;a href=&quot;#&quot;&gt;&lt;\/a&gt;&lt;\/li&gt;\r\n&lt;li class=&quot;paypal&quot;&gt;&lt;a href=&quot;#&quot;&gt;&lt;\/a&gt;&lt;\/li&gt;\r\n&lt;li class=&quot;mastercard&quot;&gt;&lt;a href=&quot;#&quot;&gt;&lt;\/a&gt;&lt;\/li&gt;\r\n&lt;li class=&quot;discover&quot;&gt;&lt;a href=&quot;#&quot;&gt;&lt;\/a&gt;&lt;\/li&gt;\r\n&lt;li class=&quot;americanexpress&quot;&gt;&lt;a href=&quot;#&quot;&gt;&lt;\/a&gt;&lt;\/li&gt;\r\n&lt;\/ul&gt;\r\n&lt;\/div&gt;\r\n&lt;\/div&gt;"}},"status":"1"}');
INSERT INTO `oc_module` (module_id,name,code,setting) VALUES (39,'Footer-Newsletter-Text ','html','{"name":"Footer-Newsletter-Text ","module_description":{"1":{"title":"","description":"&lt;p&gt;&lt;span style=&quot;color: rgb(85, 85, 85); font-family: &amp;quot;Open Sans&amp;quot;, Helvetica, sans-serif; font-size: 14px;&quot;&gt;Contrary to popular belief, Lorem Ipsum Latin Latin from.&lt;\/span&gt;&lt;br&gt;&lt;\/p&gt;"}},"status":"1"}');
INSERT INTO `oc_module` (module_id,name,code,setting) VALUES (40,'FooterRight-Contact-CMS ','html','{"name":"FooterRight-Contact-CMS ","module_description":{"1":{"title":"","description":"&lt;div id=&quot;contact&quot; class=&quot;col-sm-3 column&quot;&gt;\r\n&lt;h5 class=&quot;&quot;&gt;company info&lt;\/h5&gt;\r\n&lt;ul&gt;\r\n&lt;li&gt;&lt;div class=&quot;address&quot;&gt;&lt;i class=&quot;fa fa-map-marker&quot;&gt; &lt;\/i&gt;&lt;div class=&quot;address_content&quot;&gt;&lt;div class=&quot;contact_address&quot;&gt;507-Union Trade Centre, Beside Apple Hospital, Udhana Darwaja, Surat&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;\/li&gt;\r\n&lt;li&gt;&lt;div class=&quot;phone&quot;&gt;&lt;i class=&quot;fa fa-mobile&quot;&gt; &lt;\/i&gt;&lt;div class=&quot;contact_phone&quot;&gt;+91 8866888222&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;\/li&gt;\r\n&lt;li&gt;\r\n&lt;div class=&quot;email&quot;&gt;&lt;i class=&quot;fa fa-envelope &quot;&gt; &lt;\/i&gt;&lt;div class=&quot;contact_email&quot;&gt;&lt;a target=&quot;_blank&quot; href=&quot;#&quot;&gt;@templatemela.com&lt;\/a&gt;&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;\/li&gt;\r\n&lt;\/ul&gt;\r\n&lt;\/div&gt;"}},"status":"1"}');
INSERT INTO `oc_module` (module_id,name,code,setting) VALUES (41,'FooterTop-Assurance-CMS ','html','{"name":"FooterTop-Assurance-CMS ","module_description":{"1":{"title":"","description":"&lt;div class=&quot;footertop-cms container&quot;&gt;\r\n&lt;div class=&quot;row&quot;&gt;\r\n&lt;div class=&quot;footerblock1 footerblock&quot;&gt;\r\n&lt;div class=&quot;title&quot;&gt;special gift cards&lt;\/div&gt;\r\n&lt;div class=&quot;subtitle&quot;&gt;give the perfect gift&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;div class=&quot;footerblock2 footerblock&quot;&gt;\r\n&lt;div class=&quot;title&quot;&gt;free shipping&lt;\/div&gt;\r\n&lt;div class=&quot;subtitle&quot;&gt;on orders over $99&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;div class=&quot;footerblock3 footerblock&quot;&gt;&lt;div class=&quot;title&quot;&gt;order online&lt;\/div&gt;\r\n&lt;div class=&quot;subtitle&quot;&gt;hours : 8am - 11pm&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;div class=&quot;footerblock4 footerblock&quot;&gt;&lt;div class=&quot;title&quot;&gt;shop and save&lt;\/div&gt;\r\n&lt;div class=&quot;subtitle&quot;&gt;for all spices &amp;amp; herbs&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;\/div&gt;"}},"status":"1"}');
INSERT INTO `oc_module` (module_id,name,code,setting) VALUES (43,'Sidebar Latest','latest','{"name":"Sidebar Latest","limit":"4","width":"75","height":"100","status":"1"}');
INSERT INTO `oc_module` (module_id,name,code,setting) VALUES (44,'Sidebar Special','special','{"name":"Sidebar Special","limit":"4","width":"75","height":"100","status":"1"}');
INSERT INTO `oc_module` (module_id,name,code,setting) VALUES (45,'Category Product Tab','category_tab','{"name":"Category Product Tab","heading":"Top Category","category":"","product_category":["33","29","28"],"category_limit":"3","product_limit":"8","width":"218","height":"286","status":"1"}');
INSERT INTO `oc_module` (module_id,name,code,setting) VALUES (46,'HomePage Product Tabs','megnortabs','{"name":"HomePage Product Tabs","limit":"10","width":"216","height":"284","status":"1"}');
INSERT INTO `oc_module` (module_id,name,code,setting) VALUES (47,'Home Page Slideshow','slideshow','{"name":"Home Page Slideshow","banner_id":"7","width":"914","height":"420","status":"1"}');
INSERT INTO `oc_module` (module_id,name,code,setting) VALUES (49,'Home Page Manufacturers','banner','{"name":"Home Page Manufacturers","banner_id":"8","width":"112","height":"112","status":"1"}');
INSERT INTO `oc_module` (module_id,name,code,setting) VALUES (52,'Home Page Manufacturers','carousel','{"name":"Home Page Manufacturers","banner_id":"8","width":"112","height":"112","status":"1"}');
INSERT INTO `oc_module` (module_id,name,code,setting) VALUES (53,'Rightbanner1','banner','{"name":"Rightbanner1","banner_id":"10","width":"236","height":"350","status":"1"}');
INSERT INTO `oc_module` (module_id,name,code,setting) VALUES (54,'Column Right Testimonial CMS','html','{"name":"Column Right Testimonial CMS","module_description":{"1":{"title":"","description":"&lt;div class=&quot;testimonials&quot; id=&quot;testimonial&quot;&gt;\r\n&lt;div class=&quot;homepage-testimonial-inner&quot;&gt;\r\n&lt;div class=&quot;testimonial_inner&quot;&gt;&lt;div class=&quot;box-heading&quot;&gt;Testimonial&lt;\/div&gt;\r\n&lt;div class=&quot;homepage-testimonials-inner products box-content&quot;&gt;\r\n&lt;div class=&quot;customNavigation&quot;&gt;&lt;a class=&quot;btn prev&quot;&gt;&lt;\/a&gt;&lt;a class=&quot;btn next&quot;&gt;&lt;\/a&gt;&lt;\/div&gt;\r\n&lt;div class=&quot;products product-carousel&quot; id=&quot;testimonial-carousel&quot;&gt;\r\n&lt;div class=&quot;slider-item&quot;&gt;\r\n&lt;div class=&quot;peoplesay-block&quot;&gt;\r\n&lt;div class=&quot;test-image&quot;&gt;\r\n&lt;img src=&quot;image\/catalog\/user.jpg&quot; alt=&quot;&quot;&gt;&lt;\/div&gt;\r\n&lt;div class=&quot;testi-details&quot;&gt;&lt;a href=&quot;#&quot;&gt;Quia Voluptas&lt;\/a&gt;&lt;\/div&gt;\r\n&lt;div class=&quot;designation&quot;&gt;&lt;a href=&quot;#&quot;&gt; view tweet&lt;\/a&gt;&lt;\/div&gt;\r\n&lt;div class=&quot;test-content&quot;&gt;&lt;div class=&quot;quote-img&quot;&gt;&lt;\/div&gt;\r\n&lt;div class=&quot;test-desc&quot;&gt;&lt;p&gt;Maecenas nec fringilla felis Nulla ultrices pulvinar magna in iaculis.&lt;\/p&gt;\r\n&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;div class=&quot;slider-item&quot;&gt;\r\n&lt;div class=&quot;peoplesay-block&quot;&gt;\r\n&lt;div class=&quot;test-image&quot;&gt;\r\n&lt;img src=&quot;image\/catalog\/user.jpg&quot; alt=&quot;&quot;&gt;&lt;\/div&gt;\r\n&lt;div class=&quot;testi-details&quot;&gt;&lt;a href=&quot;#&quot;&gt;Mrtin willms&lt;\/a&gt;&lt;\/div&gt;\r\n&lt;div class=&quot;designation&quot;&gt;&lt;a href=&quot;#&quot;&gt; view tweet&lt;\/a&gt;&lt;\/div&gt;\r\n&lt;div class=&quot;test-content&quot;&gt;&lt;div class=&quot;quote-img&quot;&gt;&lt;\/div&gt;\r\n&lt;div class=&quot;test-desc&quot;&gt;&lt;p&gt;Ipsum Maecenas nec fringilla felis Nulla ultrices pulvinar magna in iaculis.&lt;\/p&gt;\r\n&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;div class=&quot;slider-item&quot;&gt;\r\n&lt;div class=&quot;peoplesay-block&quot;&gt;\r\n&lt;div class=&quot;test-image&quot;&gt;\r\n&lt;img src=&quot;image\/catalog\/user.jpg&quot; alt=&quot;&quot;&gt;&lt;\/div&gt;\r\n&lt;div class=&quot;testi-details&quot;&gt;&lt;a href=&quot;#&quot;&gt;john roy&lt;\/a&gt;&lt;\/div&gt;\r\n&lt;div class=&quot;designation&quot;&gt;&lt;a href=&quot;#&quot;&gt; view tweet&lt;\/a&gt;&lt;\/div&gt;\r\n&lt;div class=&quot;test-content&quot;&gt;&lt;div class=&quot;quote-img&quot;&gt;&lt;\/div&gt;\r\n&lt;div class=&quot;test-desc&quot;&gt;&lt;p&gt;Lorem Ipsum has been the industrys standard with dumpty Text.&lt;\/p&gt;\r\n&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;div class=&quot;testimonial_default_width&quot; style=&quot;display: none; visibility: hidden;&quot;&gt;&amp;nbsp;&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;\/div&gt;"}},"status":"1"}');
INSERT INTO `oc_module` (module_id,name,code,setting) VALUES (55,'Column-right Service Banner CMS','html','{"name":"Column-right Service Banner CMS","module_description":{"1":{"title":"","description":"&lt;div class=&quot;service-banner&quot;&gt;\r\n&lt;div class=&quot;box-heading&quot;&gt;Our Services&lt;\/div&gt;\r\n&lt;div class=&quot;box-content&quot;&gt;\r\n&lt;div class=&quot;ser-banner banner1&quot;&gt;\r\n&lt;a href=&quot;#&quot;&gt;\r\n&lt;div class=&quot;ser-text1&quot;&gt;Price&lt;\/div&gt;\r\n&lt;div class=&quot;ser-text2&quot;&gt;Delightful&lt;\/div&gt;\r\n&lt;div class=&quot;ser-text3&quot;&gt;PageMaker sheac&lt;\/div&gt;\r\n&lt;div class=&quot;round_img&quot;&gt;\r\n&lt;img src=&quot;image\/catalog\/icon_6.png&quot; alt=&quot;&quot;&gt;&lt;\/div&gt;\r\n&lt;\/a&gt;&lt;\/div&gt;\r\n&lt;div class=&quot;ser-banner banner2&quot;&gt;\r\n&lt;a href=&quot;index.php?route=product\/category&amp;amp;path=20&quot;&gt;\r\n&lt;div class=&quot;ser-text1&quot;&gt;Guides&lt;\/div&gt;\r\n&lt;div class=&quot;ser-text2&quot;&gt;Shopping&lt;\/div&gt;\r\n&lt;div class=&quot;ser-text3&quot;&gt;Dheact acthat&lt;\/div&gt;\r\n&lt;div class=&quot;round_img&quot;&gt;\r\n&lt;img src=&quot;image\/catalog\/icon_5.png&quot; alt=&quot;&quot;&gt;&lt;\/div&gt;\r\n&lt;\/a&gt;&lt;\/div&gt;\r\n&lt;div class=&quot;ser-banner banner3&quot;&gt;\r\n&lt;a href=&quot;index.php?route=account\/login&quot;&gt;\r\n&lt;div class=&quot;ser-text1&quot;&gt;Login&lt;\/div&gt;\r\n&lt;div class=&quot;ser-text2&quot;&gt;Checkout&lt;\/div&gt;\r\n&lt;div class=&quot;ser-text3&quot;&gt;All payment service&lt;\/div&gt;\r\n&lt;div class=&quot;round_img&quot;&gt;\r\n&lt;img src=&quot;image\/catalog\/icon_4.png&quot; alt=&quot;&quot;&gt;&lt;\/div&gt;\r\n&lt;\/a&gt;&lt;\/div&gt;\r\n&lt;div class=&quot;ser-banner banner4&quot;&gt;\r\n&lt;a href=&quot;#&quot;&gt;\r\n&lt;div class=&quot;ser-text1&quot;&gt;Free&lt;\/div&gt;\r\n&lt;div class=&quot;ser-text2&quot;&gt;Delivery&lt;\/div&gt;\r\n&lt;div class=&quot;ser-text3&quot;&gt;Mobile Application&lt;\/div&gt;\r\n&lt;div class=&quot;round_img&quot;&gt;\r\n&lt;img src=&quot;image\/catalog\/icon_3.png&quot; alt=&quot;&quot;&gt;&lt;\/div&gt;\r\n&lt;\/a&gt;&lt;\/div&gt;\r\n&lt;div class=&quot;ser-banner banner5&quot;&gt;\r\n&lt;a href=&quot;OPC2\/index.php?route=account\/register&quot;&gt;\r\n&lt;div class=&quot;ser-text1&quot;&gt;Register&lt;\/div&gt;\r\n&lt;div class=&quot;ser-text2&quot;&gt;My Details&lt;\/div&gt;\r\n&lt;div class=&quot;ser-text3&quot;&gt;Your Bank Account&lt;\/div&gt;\r\n&lt;div class=&quot;round_img&quot;&gt;\r\n&lt;img src=&quot;image\/catalog\/icon_2.png&quot; alt=&quot;&quot;&gt;&lt;\/div&gt;\r\n&lt;\/a&gt;&lt;\/div&gt;\r\n&lt;div class=&quot;ser-banner banner6&quot;&gt;\r\n&lt;a href=&quot;#&quot;&gt;\r\n&lt;div class=&quot;ser-text1&quot;&gt;Mobile&lt;\/div&gt;\r\n&lt;div class=&quot;ser-text2&quot;&gt;Marketing&lt;\/div&gt;\r\n&lt;div class=&quot;ser-text3&quot;&gt;PageMaker she&lt;\/div&gt;\r\n&lt;div class=&quot;round_img&quot;&gt;\r\n&lt;img src=&quot;image\/catalog\/icon_1.png&quot; alt=&quot;&quot;&gt;&lt;\/div&gt;\r\n&lt;\/a&gt;&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;\/div&gt;"}},"status":"1"}');
INSERT INTO `oc_module` (module_id,name,code,setting) VALUES (56,'HomePage Banner CMS','html','{"name":"HomePage Banner CMS","module_description":{"1":{"title":"","description":"&lt;div class=&quot;subbanner-cms2&quot;&gt;\r\n&lt;div class=&quot;sub-heading row&quot;&gt;Catchy offers&lt;\/div&gt;\r\n&lt;div class=&quot;subbanner-inner&quot;&gt; \r\n&lt;div class=&quot;subbannerpart1&quot;&gt;\r\n&lt;div class=&quot;subbanner-one&quot;&gt; \r\n&lt;div class=&quot;content-inner&quot;&gt; \r\n&lt;a href=&quot;#&quot;&gt;&lt;img src=&quot;image\/catalog\/small_banner2.jpg&quot; alt=&quot;&quot;&gt;&lt;\/a&gt; \r\n&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;div class=&quot;subbannerpart2&quot;&gt; \r\n&lt;div class=&quot;subbanner-two&quot;&gt; \r\n&lt;div class=&quot;content-inner&quot;&gt; \r\n&lt;div class=&quot;img1&quot;&gt; \r\n&lt;a href=&quot;#&quot;&gt;&lt;img src=&quot;image\/catalog\/small_banner3.jpg&quot; alt=&quot;&quot;&gt;&lt;\/a&gt; \r\n&lt;\/div&gt;\r\n&lt;div class=&quot;img2&quot;&gt;\r\n&lt;a href=&quot;#&quot;&gt;&lt;img src=&quot;image\/catalog\/small_banner4.jpg&quot; alt=&quot;&quot;&gt;&lt;\/a&gt; \r\n&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;\/div&gt;\r\n&lt;\/div&gt;"}},"status":"1"}');
INSERT INTO `oc_module` (module_id,name,code,setting) VALUES (57,'Sidebar Featured','featured','{"name":"Sidebar Featured","product_name":"","product":["42","47","28","41"],"limit":"4","width":"75","height":"100","status":"1"}');
INSERT INTO `oc_module` (module_id,name,code,setting) VALUES (58,'HomePage Bestseller','bestseller','{"name":"HomePage Bestseller","limit":"10","width":"218","height":"286","status":"1"}');
INSERT INTO `oc_module` (module_id,name,code,setting) VALUES (60,'Special Products','special','{"name":"Special Products","limit":"4","width":"75","height":"100","status":"1"}');
INSERT INTO `oc_module` (module_id,name,code,setting) VALUES (61,'Rightbanner2','banner','{"name":"Rightbanner2","banner_id":"11","width":"236","height":"342","status":"1"}');
INSERT INTO `oc_module` (module_id,name,code,setting) VALUES (62,'Manufacturers','banner','{"name":"Manufacturers","banner_id":"8","width":"112","height":"112","status":"1"}');
INSERT INTO `oc_module` (module_id,name,code,setting) VALUES (63,'Sidebar Bestseller','bestseller','{"name":"Sidebar Bestseller","limit":"3","width":"75","height":"100","status":"1"}');


truncate table oc_layout_module;

INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (215,5,'megnorcategory','column_left',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (216,5,'special.44','column_left',1);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (217,5,'search_suggestion','content_top',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (218,5,'html.41','footertop',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (219,5,'html.38','footerbottom',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (220,5,'html.40','footerright',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (221,5,'html.39','footernewstext',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (222,5,'html.35','headertop',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (223,5,'html.36','headertop',1);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (224,5,'html.32','headertopleft',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (225,2,'megnorcategory','column_left',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (226,2,'latest.43','column_left',1);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (227,2,'special.44','column_left',2);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (228,2,'search_suggestion','content_top',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (229,2,'html.41','footertop',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (230,2,'html.38','footerbottom',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (231,2,'html.40','footerright',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (232,2,'html.39','footernewstext',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (233,2,'html.35','headertop',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (234,2,'html.36','headertop',1);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (235,2,'html.32','headertopleft',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (236,13,'megnorcategory','column_left',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (237,13,'latest.43','column_left',1);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (238,13,'special.44','column_left',2);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (239,13,'information','column_left',3);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (240,13,'search_suggestion','content_top',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (241,13,'html.41','footertop',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (242,13,'html.38','footerbottom',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (243,13,'html.40','footerright',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (244,13,'html.39','footernewstext',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (245,13,'html.35','headertop',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (246,13,'html.36','headertop',1);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (247,13,'html.32','headertopleft',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (248,9,'megnorcategory','column_left',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (249,9,'information','column_left',1);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (250,9,'search_suggestion','content_top',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (251,9,'html.41','footertop',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (252,9,'html.38','footerbottom',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (253,9,'html.40','footerright',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (254,9,'html.39','footernewstext',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (255,9,'html.35','headertop',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (256,9,'html.36','headertop',1);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (257,9,'html.32','headertopleft',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (288,10,'search_suggestion','content_top',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (289,10,'html.41','footertop',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (290,10,'html.38','footerbottom',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (291,10,'html.39','footernewstext',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (292,10,'html.40','footerright',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (293,10,'account','column_right',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (294,10,'information','column_right',1);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (295,6,'search_suggestion','content_top',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (296,6,'html.41','footertop',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (297,6,'html.38','footerbottom',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (298,6,'html.39','footernewstext',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (299,6,'html.40','footerright',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (300,6,'account','column_right',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (301,6,'information','column_right',1);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (334,7,'search_suggestion','content_top',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (335,7,'html.41','footertop',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (336,7,'html.38','footerbottom',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (337,7,'html.39','footernewstext',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (338,7,'html.40','footerright',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (339,7,'information','column_right',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (340,7,'latest.43','column_right',1);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (341,12,'search_suggestion','content_top',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (342,12,'html.41','footertop',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (343,12,'html.38','footerbottom',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (344,12,'html.39','footernewstext',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (345,12,'html.40','footerright',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (346,12,'information','column_right',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (347,12,'latest.43','column_right',1);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (360,3,'search_suggestion','content_top',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (361,3,'category','column_right',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (362,3,'account','column_right',1);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (364,3,'banner.61','column_right',3);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (365,8,'search_suggestion','content_top',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (366,8,'html.41','footertop',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (367,8,'html.38','footerbottom',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (368,8,'html.39','footernewstext',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (369,8,'html.40','footerright',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (370,8,'information','column_right',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (372,4,'account','content_top',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (373,4,'search_suggestion','content_top',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (374,4,'account','content_top',1);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (375,4,'html.41','footertop',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (376,4,'html.38','footerbottom',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (377,4,'html.39','footernewstext',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (378,4,'html.40','footerright',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (379,4,'account','footerright',1);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (380,4,'information','column_right',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (381,4,'latest.43','column_right',1);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (382,11,'search_suggestion','content_top',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (383,11,'html.41','footertop',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (384,11,'html.38','footerbottom',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (385,11,'html.39','footernewstext',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (386,11,'html.40','footerright',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (387,11,'information','column_right',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (388,11,'special.44','column_right',1);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (428,1,'search_suggestion','content_top',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (429,1,'slideshow.47','content_top',1);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (430,1,'banner.31','content_top',2);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (431,1,'category_tab.45','content_top',3);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (432,1,'featured.28','content_top',4);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (433,1,'html.56','content_top',5);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (434,1,'html.37','content_top',6);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (435,1,'bestseller.58','content_top',7);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (436,1,'banner.49','content_top',8);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (437,1,'html.41','footertop',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (438,1,'html.38','footerbottom',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (439,1,'html.39','footernewstext',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (440,1,'html.40','footerright',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (441,1,'newsletters','footerright',1);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (442,1,'html.55','column_right',0);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (443,1,'banner.53','column_right',1);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (444,1,'latest.43','column_right',2);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (445,1,'banner.61','column_right',3);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (446,1,'special.44','column_right',4);
INSERT INTO `oc_layout_module` (layout_module_id,layout_id,code,position,sort_order) VALUES (447,1,'html.54','column_right',5);


truncate table oc_layout_route;


INSERT INTO `oc_layout_route` (layout_route_id,layout_id,store_id,route) VALUES (67,5,0,'product/manufacturer');
INSERT INTO `oc_layout_route` (layout_route_id,layout_id,store_id,route) VALUES (68,2,0,'product/product');
INSERT INTO `oc_layout_route` (layout_route_id,layout_id,store_id,route) VALUES (69,13,0,'product/search');
INSERT INTO `oc_layout_route` (layout_route_id,layout_id,store_id,route) VALUES (70,9,0,'information/sitemap');
INSERT INTO `oc_layout_route` (layout_route_id,layout_id,store_id,route) VALUES (75,10,0,'affiliate/%');
INSERT INTO `oc_layout_route` (layout_route_id,layout_id,store_id,route) VALUES (76,6,0,'account/%');
INSERT INTO `oc_layout_route` (layout_route_id,layout_id,store_id,route) VALUES (80,7,0,'checkout/%');
INSERT INTO `oc_layout_route` (layout_route_id,layout_id,store_id,route) VALUES (81,12,0,'product/compare');
INSERT INTO `oc_layout_route` (layout_route_id,layout_id,store_id,route) VALUES (83,3,0,'product/category');
INSERT INTO `oc_layout_route` (layout_route_id,layout_id,store_id,route) VALUES (84,8,0,'information/contact');
INSERT INTO `oc_layout_route` (layout_route_id,layout_id,store_id,route) VALUES (85,4,0,'');
INSERT INTO `oc_layout_route` (layout_route_id,layout_id,store_id,route) VALUES (86,11,0,'information/information');
INSERT INTO `oc_layout_route` (layout_route_id,layout_id,store_id,route) VALUES (89,1,0,'common/home');
